import "./Select";
import "./Table";
import "./Settings";
import "./Config";
import "./Password";
import "./Alias";
import "./Sample";
import "./Offpeak";
import "./Rules";
import "./Store";
import './Update'